### PR TITLE
Initial work on `train_and_evaluate()`

### PR DESCRIPTION
**Pull request by terrytangyuan**
This PR adds support for `train_and_evaluate()` for estimators. Though they are not exported yet until they are more stable. 

A couple of questions:

1. For `train_spec` and `eval_spec`, we'd want to integrate with `tfruns` by adding the view_metrics, history, etc. into the hooks. We can use [these methods](https://github.com/rstudio/tfestimators/blob/master/R/utils_tf.R#L112-L141) that I refactored earlier from `train()` and `evaluate()` that can be re-used by `train_spec` and `eval_spec`. However, I want to double check with you to see if you have any concerns that `.globals$history` that we are using to save training history and metrics may not work correctly under distributed settings. 

2. Do you have concerns over the fact that `train_spec` and `eval_spec` are lazily evaluated (on the R side only) since we need to toggle the correct input_fn to use using the `estimator`'s class inside `train_and_evaluate()`. 

3. The default for `train_spec`'s `max_steps` is `NULL` in Python API,  which trains forever (same behavior as `train.tf_estimator`). Do you think we should change this to something small (e.g. `2`) on the R side? This will perhaps make it less confusing for R users but on the other hand inconsistent with the Python API. What are your opinions?

A couple of TODOs:

1. A vignette for example usages for local and distributed settings. 
2. Support additional arguments for `verbose` and `view_metrics` to integrate with tfruns.

### CODE REVIEW

**Comment by jjallaire** [comment]
I don't have any concerns about the lazy evaluation of the train_spec and eval_spec (since already do that sort of thing with input_fn -- don't see an easy way around it).

In terms of `.globals$history` and distributed training, I'm not familiar enough with how distributed training works to say. What do you think the idea behavior is and what are the obstacles to achieving it?

In general I don't want to deviate from the Python defaults. What would be the motivator for setting a different default in R?

**Comment by jjallaire** [comment]
Does `train_and_evaluate` pass any context to scripts about the number of shards and current shard index?  If so that we can combine that with `Dataset.shard` to automatically route input files to the correct worker: https://www.tensorflow.org/versions/master/api_docs/python/tf/data/Dataset#shard

**Comment by terrytangyuan** [comment]
Let's keep the defaults consistent then. 

In terms of `.globals$history` and distributed training, I think it's fine since it's just a regular variable in R. If it's tensor then we need to be more careful there to properly handle the communications between parameter servers and workers. But nothing to be concerned here yet. I will keep an eye on it. 

Regarding `Dataset.shard`, good question - I am not too sure. Estimators [use cpu:0](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/estimator.py#L666) for operations inside the input_fn. I think Estimator does not shard the input but creates replicas that then get distributed across workers for asynchronous training and fault tolerance.

**Comment by terrytangyuan** [comment]
Do you mind if I merge this in (these new functions are not exported) and then work on other remaining TODOs in new PRs? This way I can avoid conflicts with the other pending PR: https://github.com/rstudio/tfestimators/pull/106

**Comment by terrytangyuan** [comment]
There might be ongoing efforts internally for supporting `Dataset.shard` integration with Estimator's `RunConfig`. Estimators need to support other types of distributed training as well.

**Comment by jjallaire** [comment]
Yes it's fine if we merge now

**Pull request merged**
