### PR TITLE
better track duplicated feature columns

### LINKED ISSUE #96: `crossed_columns` assume a `key` attribute, but some objects do not have this attribute
Firstly I would like to thank you for all the great works in this package!

This issue concerns (or appears in) the [example wide and deep](https://github.com/rstudio/tfestimators/blob/master/vignettes/examples/wide_and_deep.R).

I run everything in the example, but the instruction produces an error:
```
crossed_columns <- feature_columns(
  native_country, education, occupation, workclass, relationship, age_buckets,
  column_crossed(c("education", "occupation"), hash_bucket_size = 10000),
  column_crossed(c("native_country", "occupation"), hash_bucket_size = 10000),
  column_crossed(c(age_buckets, "education", "occupation"), hash_bucket_size = 10000)
)
#Error in py_get_attr_impl(x, name, silent) : 
#  AttributeError: '_BucketizedColumn' object has no attribute 'key'
```

The function `crossed_columns` seems to manage objects with a `key` attribute (I guess it from the meaning of the error and the [source code](https://github.com/rstudio/tfestimators/blob/4c4c1798fa8d9f84fcddd69513c30e83dbb0f8bb/R/feature_columns.R#L52)) , but this is not the case of `age_buckets` (nor `column_crossed(c("education", "occupation"), hash_bucket_size = 10000)`, `  column_crossed(c("native_country", "occupation"), hash_bucket_size = 10000)` and `column_crossed(c(age_buckets, "education", "occupation"), hash_bucket_size = 10000)` which have a `keys` attributes but not a `key` attribute).

For infromation:
```
sessionInfo()
# R version 3.4.1 (2017-06-30)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 7 x64 (build 7601) Service Pack 1
# 
# Matrix products: default
# 
# locale:
#   [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
# [3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
# [5] LC_TIME=French_France.1252    
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
#   [1] tfestimators_0.1.2.9000
# 
# loaded via a namespace (and not attached):
#   [1] Rcpp_0.12.13          dplyr_0.7.2           assertthat_0.2.0     
# [4] R6_2.2.2              jsonlite_1.5          magrittr_1.5         
# [7] tfruns_0.9.1          rlang_0.1.2           curl_2.8.1           
# [10] bindrcpp_0.2          reticulate_1.2        tools_3.4.1          
# [13] glue_1.1.1            purrr_0.2.3           compiler_3.4.1       
# [16] pkgconfig_2.0.1       tensorflow_1.4        bindr_0.1            
# [19] tidyselect_0.2.0.9000 tibble_1.3.4  



reticulate::py_config()
# python:         C:\Users\Dominique\Anaconda3\envs\r-tensorflow\python.exe
# libpython:      C:/Users/Dominique/Anaconda3/envs/r-tensorflow/python36.dll
# pythonhome:     C:\Users\DOMINI~1\ANACON~1\envs\R-TENS~1
# version:        3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
# Architecture:   64bit
# numpy:          C:\Users\DOMINI~1\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
# numpy_version:  1.13.3
# tensorflow:     C:\Users\DOMINI~1\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow
# 
# python versions found: 
#   C:\Users\Dominique\Anaconda3\envs\r-tensorflow\python.exe
# C:\Users\DOMINI~1\ANACON~1\python.exe
```
Thanks a lot
Dom

### PR DESCRIPTION
**Pull request by kevinushey**
Should fix #96.

### CODE REVIEW

**Comment by jjallaire** [comment]
Let's re-target this fix for the v1.3.0 branch (that's what users are installing now since master depends on TF v1.4) then we can just keep merging v1.3.0 into master to pickup fixes as they are made.

**Comment by kevinushey** [comment]
Okay, fixed up PR and retargeted for v1.3.0 branch.

Hopefully in the future we're planning to have one version of `tfestimators` that works with all versions of TensorFlow (down to some minimum version)?

**Comment by terrytangyuan** [comment]
Thanks! Regarding backward compatibility, I am not sure what the best way is to maintain that. For example, if a function can now accept one additional argument for v1.4, we'd have to wrap that function in another alternative Python API calls in an if-else (e.g. if users needs to use that additional new argument). We don't want to use ... here since we need to document the new signature as well as doing some potential validation to the new argument. Do you have any suggested way to do that?

**Comment by jjallaire** [comment]
Our principle is that all versions of our R wrapper packages should work with the current TF version (dev master if possible) as well as all previous versions back to some threshold. For example, the tensorflow package works on all versions of tensorflow back to v1.0 and the Keras package works on all versions of Keras from 2.0.8 all the way back to 2.0.0. If we don't do this it becomes very awkward for both devs and end users (as we are now experiencing with tfestimators).

The keras package has many examples of how to support newer versions while still not failing against older version. In your example of an argument being added, we simply switch our calling semantics to `do.call` and conditionally include the new argument. For example here (https://github.com/rstudio/keras/blob/master/R/model.R#L613-L625):

```r
predict_generator <- function(object, generator, steps, max_queue_size = 10, verbose = 0) {
  
  args <- list(
    generator = generator,
    steps = as.integer(steps),
    max_queue_size = as.integer(max_queue_size)
  )
  
  if (keras_version() >= "2.0.1")
    args$verbose <- as.integer(verbose)
  
  call_generator_function(object$predict_generator, args)
}
```

In this case I am silently ignore the argument in earlier versions. This might be okay or we depending on what the argument is you might want to checking for `!missing` and issue a warning. 

You could also have functions which bomb out entirely if the right version isn't available. The main idea is that given the way the R package system works (users tend to get forced to the latest version by CRAN + availability of bug fixes) we can't afford to tie our R package versions to the latest Python package versions.

I had assumed that the reason for our v1.3.0 branch was some fundamental incompatibility with TF v1.4. If however the only concern is new arguments or some functions that require TF v1.4 we should just add the conditional code like that above required to enable everyone to develop on and use the master branch. @terrytangyuan Could you take a shot at this?

**Comment by terrytangyuan** [comment]
Got it! Yes, I will take a shot at this and make sure master branch is
compatible for both.

**Pull request merged**
